name: Publish Nuget

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v5

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.x' # Adjust to match your target .NET version

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore src/Qonq.BlueSky/Qonq.BlueSky.csproj

      - name: Build project
        run: dotnet build src/Qonq.BlueSky/Qonq.BlueSky.csproj --configuration Release --no-restore

      - name: Pack NuGet package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          echo "Generating build number..."
          BUILD_NUMBER=$(date +%Y.%m.%d).${{ github.run_number }}
          echo "Build number: $BUILD_NUMBER"

          dotnet pack src/Qonq.BlueSky/Qonq.BlueSky.csproj --configuration Release --no-build -o ./nupkgs /property:PackageVersion=$BUILD_NUMBER
          dotnet nuget push --source 'https://nuget.org' --api-key $NUGET_API_KEY nupkgs/*.nupkg